config/routes.rb
Rails.application.routes.draw do
  
  resources :questionnaires, shallow: true do
    resources :questions do
      resources :choices
    end
  end

  resources :users, only: [:index, :show, :update, :edit]
  resources :quizzes

  get 'home/index'
  root 'home#index'

  get "/login", to: redirect("/auth/google_oauth2")
  get "/logout", to: "sessions#destroy"
  get "/auth/google_oauth2/callback", to: "sessions#create"
  resource :session, only: [:create, :destroy]

  # resources :answers
  
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :choices, dependent: :restrict_with_error
  belongs_to :questionnaire

  validates :kind, :name, presence: true

  KINDS = %w(boolean checkbox text radiobutton multitext)

  def to_s
    name
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_questionnaire, except: [:show, :edit, :update, :destroy]
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  def index
    @questions = policy_scope(@questionnaire.questions)
  end

  def show
  end

  def new
    @question = @questionnaire.questions.new
    authorize @question
  end

  def edit
  end

  def create
    @question = @questionnaire.questions.new(question_params)
    authorize @question
    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to [@questionnaire, @question], notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: [@questionnaire, @question] }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questionnaire_questions_url(@question.questionnaire), notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_question
      @question = Question.find(params[:id])
      authorize @question
    end

    def question_params
      params.require(:question).permit(:kind, :name, :body)
    end

    def set_questionnaire
      @questionnaire = Questionnaire.find(params[:questionnaire_id])
    end
end

app/views/questions/_form.html.slim
= form_for [@questionnaire, @question] do |f|
  = render 'layouts/error_explanation', f: f

  = form_group_for f, :kind, label: :kind, control_class: "select" do
    = f.select :kind, Question::KINDS, include_blank: true

  = form_group_for f, :name, label: :name do
    = f.text_field :name, class: "input"

  = form_group_for f, :body, label: :body do
    = f.text_area :body, class: "textarea"

  .field = f.submit class:"button is-link"

app/views/questions/edit.html.slim
h1.title Modificando pregunta 

== render 'form'

=> link_to 'Show', @question
'|
=< link_to 'Back', questionnaire_questions_path(@question)

app/views/questions/index.html.slim
h1.title Preguntas (#{@questions.count})
p.subtitle 
  span> Cuestionario: 
  = link_to @questionnaire, @questionnaire

= link_to 'Nueva pregunta', new_questionnaire_question_path(@questionnaire), class:"button is-primary"

table
  thead.table.is-striped.is-narrow.is-hoverable
    tr
      th Kind
      th Name
      th Body
      th Opciones
      th
      th
      th

  tbody
    - @questions.each do |question|
      tr
        td = question.kind
        td = question.name
        td = question.body.truncate(25)
        td = link_to "#{question.choices.count} opciones", question_choices_path(question)
        td = link_to 'Show', question
        td = link_to 'Edit', edit_question_path(question)
        td = link_to 'Destroy', question, data: { confirm: 'Are you sure?' }, method: :delete

app/views/questions/new.html.slim
h1.title Nueva pregunta de #{@questionnaire}

== render 'form'

= link_to 'Back', questionnaire_questions_path(@questionnaire)

app/views/questions/show.html.slim
p
  strong Questionnarie:
  = @question.questionnaire
p
  strong Kind:
  = @question.kind
p
  strong Name:
  = @question.name
p
  strong Body:
  = @question.body

=> link_to 'Edit', edit_question_path(@question)
'|
=< link_to 'Back', questionnaire_questions_path(@question.questionnaire)