config/routes.rb
Rails.application.routes.draw do
  
  resources :questionnaires, shallow: true do
    resources :questions do
      resources :choices
    end
  end

  resources :users, only: [:index, :show, :update, :edit]
  resources :quizzes

  get 'home/index'
  root 'home#index'

  get "/login", to: redirect("/auth/google_oauth2")
  get "/logout", to: "sessions#destroy"
  get "/auth/google_oauth2/callback", to: "sessions#create"
  resource :session, only: [:create, :destroy]

  # resources :answers
  
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :question
  validates :body, presence: true
  def to_s
    body
  end
end

app/controllers/choices_controller.rb
class ChoicesController < ApplicationController
  before_action :set_question, except: [:show, :edit, :update, :destroy]
  before_action :set_choice, only: [:show, :edit, :update, :destroy]

  # GET /choices
  # GET /choices.json
  def index
    @choices = @question.choices
  end

  # GET /choices/1
  # GET /choices/1.json
  def show
  end

  # GET /choices/new
  def new
    @choice = @question.choices.new
    authorize @choice
  end

  # GET /choices/1/edit
  def edit
  end

  # POST /choices
  # POST /choices.json
  def create
    @choice = @question.choices.new(choice_params)
    authorize @choice
    respond_to do |format|
      if @choice.save
        format.html { redirect_to question_choices_path(@question), notice: 'Choice was successfully created.' }
        format.json { render :show, status: :created, location: question_choices_path(@question) }
      else
        format.html { render :new }
        format.json { render json: @choice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /choices/1
  # PATCH/PUT /choices/1.json
  def update
    respond_to do |format|
      if @choice.update(choice_params)
        format.html { redirect_to question_choices_path(@choice.question), notice: 'Choice was successfully updated.' }
        format.json { render :show, status: :ok, location: question_choices_path(@choice.question) }
      else
        format.html { render :edit }
        format.json { render json: @choice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /choices/1
  # DELETE /choices/1.json
  def destroy
    @choice.destroy
    respond_to do |format|
      format.html { redirect_to question_choices_url(@choice.question), notice: 'Choice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_choice
      @choice = Choice.find(params[:id])
      authorize @choice
    end

    def set_question
      @question = Question.find(params[:question_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def choice_params
      params.require(:choice).permit(:body, :score)
    end

  end

app/views/choices/_form.html.slim
= form_for [@question, @choice] do |f|
  = render 'layouts/error_explanation', f: f

  = form_group_for f, :body, label: :body do
    = f.text_area :body, class: "textarea"

  = form_group_for f, :score, label: :score do
    = f.text_field :score, class: "input"

  .field = f.submit class:"button is-link"

app/views/choices/edit.html.slim
h1.title Modificando opción
p.subtitle 
  span<> Pregunta: 
  = link_to @choice.question, @choice.question
  span<> Cuestionario: 
  = link_to @choice.question.questionnaire, @choice.question.questionnaire

== render 'form'

=> link_to 'Show', @choice
'|
=< link_to 'Back', question_choices_path(@choice.question)

app/views/choices/index.html.slim
h1.title Opciones (#{@choices.count})
p.subtitle 
  span<> Pregunta: 
  = link_to @question, @question
  span<> Cuestionario: 
  = link_to @question.questionnaire, questionnaire_questions_path(@question.questionnaire)

p= link_to 'Nueva opción', new_question_choice_path(@question), class:"button is-primary"

table.table.is-striped.is-narrow.is-hoverable
  thead
    tr
      th Body
      th Score
      th
      th
      th

  tbody
    - @choices.each do |choice|
      tr
        td = choice.body
        td = choice.score
        td = link_to 'Show', choice
        td = link_to 'Edit', edit_choice_path(choice)
        td = link_to 'Destroy', choice, data: { confirm: 'Are you sure?' }, method: :delete

app/views/choices/new.html.slim
h1.title Nueva opción
p.subtitle 
  span<> Pregunta: 
  = link_to @question, @question
  span<> Cuestionario: 
  = link_to @question.questionnaire, @question.questionnaire

== render 'form'

= link_to 'Back', question_choices_path(@question)

app/views/choices/show.html.slim
p
  strong Question:
  = @choice.question
p
  strong Body:
  = @choice.body
  
- if current_user.admin?
  p
    strong Score:
    = @choice.score
  p
    strong Comments:
    = @choice.comments

=> link_to 'Ver/modificar respuestas', edit_choice_path(@choice)
'|
=< link_to 'Regresar', question_choices_path(@choice.question)