config/routes.rb
Rails.application.routes.draw do
  
  resources :questionnaires, shallow: true do
    resources :questions do
      resources :choices
    end
  end

  resources :users, only: [:index, :show, :update, :edit]
  resources :quizzes

  get 'home/index'
  root 'home#index'

  get "/login", to: redirect("/auth/google_oauth2")
  get "/logout", to: "sessions#destroy"
  get "/auth/google_oauth2/callback", to: "sessions#create"
  resource :session, only: [:create, :destroy]

  # resources :answers
  
end

app/models/questionnaire.rb
class Questionnaire < ApplicationRecord
  has_many :questions, dependent: :restrict_with_error
  has_many :quizzes, dependent: :restrict_with_error
  validates :name, presence: true

  def to_s
    name
  end
  
end

app/controllers/questionnaires_controller.rb
class QuestionnairesController < ApplicationController
  before_action :set_questionnaire, only: [:show, :edit, :update, :destroy]

  def index
    @questionnaires = policy_scope(Questionnaire.all)
  end

  def show
  end

  def new
    @questionnaire = Questionnaire.new
    authorize @questionnaire
  end

  def edit
  end

  def create
    @questionnaire = Questionnaire.new(questionnaire_params)
    authorize @questionnaire
    respond_to do |format|
      if @questionnaire.save
        format.html { redirect_to @questionnaire, notice: 'Questionnaire was successfully created.' }
        format.json { render :show, status: :created, location: @questionnaire }
      else
        format.html { render :new }
        format.json { render json: @questionnaire.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @questionnaire.update(questionnaire_params)
        format.html { redirect_to @questionnaire, notice: 'Questionnaire was successfully updated.' }
        format.json { render :show, status: :ok, location: @questionnaire }
      else
        format.html { render :edit }
        format.json { render json: @questionnaire.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @questionnaire.destroy
    respond_to do |format|
      format.html { redirect_to questionnaires_url, notice: 'Questionnaire was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_questionnaire
      @questionnaire = Questionnaire.find(params[:id])
      authorize @questionnaire
    end

    def questionnaire_params
      params.require(:questionnaire).permit(:name, :instructions)
    end
end

app/views/questionnaires/_form.html.slim
= form_for @questionnaire do |f|
  = render 'layouts/error_explanation', f: f

  = form_group_for f, :name, label: :name do
    = f.text_field :name, class: "input"

  = form_group_for f, :instructions, label: :instructions do
    = f.text_area :instructions, class: "textarea"

  .field = f.submit class:"button is-link"

app/views/questionnaires/edit.html.slim
h1.title Modificando cuestionario id #{@questionnaire.id}

== render 'form'

=> link_to 'Show', @questionnaire
'|
=< link_to 'Back', questionnaires_path

app/views/questionnaires/index.html.slim
h1.title Cuestionarios (#{Questionnaire.count})

p= link_to 'New Questionnaire', new_questionnaire_path, class:"button is-primary"

table.table.is-striped.is-narrow.is-hoverable
  thead
    tr
      th Name
      th Instructions
      th Questions
      th
      th
      th

  tbody
    - @questionnaires.each do |questionnaire|
      tr
        td = questionnaire.name
        td = questionnaire.instructions
        td 
          = link_to "#{questionnaire.questions.count} Questions", questionnaire_questions_path(questionnaire)
        td = link_to 'Show', questionnaire
        td = link_to 'Edit', edit_questionnaire_path(questionnaire)
        td = link_to 'Destroy', questionnaire, data: { confirm: 'Are you sure?' }, method: :delete

app/views/questionnaires/new.html.slim
h1.title Nuevo cuestionario

== render 'form'

app/views/questionnaires/show.html.slim
h1.title Questionario id#{@questionnaire.id} #{@questionnaire.name} 
p
  strong Instructions:
  = @questionnaire.instructions

=> link_to 'Edit', edit_questionnaire_path(@questionnaire)
'|
=< link_to 'Back', questionnaires_path